//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Smartrac.SmartCosmos.ClientEndpoint.Base")]
[assembly: AssemblyCompany("SMARTRAC TECHNOLOGY GROUP")]
[assembly: AssemblyProduct("Smartrac.SmartCosmos.ClientEndpoint.Base")]
[assembly: AssemblyDescription("Smartrac.SmartCosmos.ClientEndpoint.Base")]
[assembly: AssemblyCopyright("© 2014 SMARTRAC TECHNOLOGY GROUP")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]


